latest build

diff --git a/build-bin/maven/maven_opts b/build-bin/maven/maven_opts
--- a/build-bin/maven/maven_opts
+++ b/build-bin/maven/maven_opts
@@ -13,11 +13,29 @@
 # the License.
 #
 
-set -ue
+# This script checks each variable value, so it isn't important to fail on unbound (set -u)
+set -e
 
-# This script prepares GPG, needed to sign jars for Sonatype deployment during `maven_deploy`
+maven_project_basedir=${MAVEN_PROJECT_BASEDIR:-.}
+pom="${maven_project_basedir}/pom.xml"
 
-# ensure GPG commands work non-interactively
-export GPG_TTY=$(tty)
-# import signing key used for jar files
-echo ${GPG_SIGNING_KEY} | base64 --decode | gpg --batch --passphrase ${GPG_PASSPHRASE} --import
+# fail if there's no pom
+test -f "${pom}"
+
+arch=$(uname -m)
+case ${arch} in
+  arm64* )
+    arch=arm64
+    ;;
+  aarch64* )
+    arch=arm64
+    ;;
+esac
+
+maven_opts="${MAVEN_OPTS:-}"
+if [ ${arch} = "arm64" ] && [ -f /etc/alpine-release ]; then
+  # Defensively avoid arm64+alpine problems with posix_spawn
+  maven_opts="${maven_opts} -Djdk.lang.Process.launchMechanism=vfork"
+fi
+
+echo ${maven_opts}
